<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllInfo()
	{
		$query = $this->getEntityManager()
					->createQuery('
						SELECT p, c, n FROM AppBundle:Product p
						JOIN p.category c
						JOIN p.product_comments n
						WHERE c.id = p.category
						AND n.product = p.id');

		try {
			return $query->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
